# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rana King Art
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  An awesome description for Rana King Art here. 
  You can edit this line info anytime you want.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

logo: /siteicon.png
author:
  name: Rana King
  email: info@ranaking.art
social:
  name: Rana King Art
  links:
    - https://github.com/RanaKingArt/RanaKingArt.github.io

# Formspree info for contact form
formspree: mdowrwrw

# Page defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /images/me.jpg
  - scope:
      path: "index.html"
    values:
      text_width: false


# Build settings
markdown: kramdown

# Pretty Page Links
permalink: pretty

# Whitelisted plugins only!
# GitHub Pages: https://pages.github.com/versions/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  # Additionals
  - README.md
  # Defaults
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Google Analytics
google_analytics_key:
